# just --working-directory . --justfile test/justfile

default: test lint typecheck

test:
  pytest --cov --cov-report=term-missing

coverage:
  pytest --cov --cov-report=html
  open htmlcov/index.html

lint:
  pylint src

typecheck:
  mypy src
